<?php
/*
Template Name: Flight Template
*/
get_header(); // Include the common header
?>

<body>
    <!-- Content of the other page -->

    <!-- Example PHP-generated content with the additional styles -->
    <div class="booking-info">
        <h2>Booking Information</h2>
        <p>This is some example content generated by PHP.</p>
        <ul>
            <li><strong>Date:</strong> <?= date("F j, Y"); ?></li>
            <li><strong>Time:</strong> <?= date("g:i A"); ?></li>
            <li><strong>Location:</strong> Your Venue</li>
        </ul>
    </div>

    <!-- Include the Footer -->
    <?php get_footer(); // Include the common footer ?>
</body>

</html>